name: nqe
version: 0.6.3
synopsis: Concurrency library in the style of Erlang/OTP
description: Please see the README on GitHub at <https://github.com/jprupp/nqe#readme>
category: Control
author: Jean-Pierre Rupp
maintainer: xenog@protonmail.com
license: MIT
license-file: LICENSE
github: xenog/nqe
extra-source-files:
  - README.md
  - CHANGELOG.md
dependencies:
  - base >=4.8 && <5
  - conduit
  - stm
  - unliftio
library:
  source-dirs: src
  dependencies:
    - containers
    - hashable
    - mtl
    - unique
tests:
  nqe-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - async
      - bytestring
      - conduit-extra
      - exceptions
      - hspec
      - nqe
      - stm-conduit
      - text
