name: nqe
version: '0.1.0.1'
synopsis: Concurrency library in the style of Erlang/OTP
description: 'Minimalistic actor library inspired by Erlang/OTP with support for supervisor hierarchies and asynchronous messages, as well as abstractions for synchronous communication and easy management of TCP connections.'
category: Control
author: Jean-Pierre Rupp
maintainer: xenog@protonmail.com
license: PublicDomain
license-file: UNLICENSE
github: xenog/nqe
extra-source-files:
- README.md
dependencies:
- bytestring
- conduit
- conduit-extra
- async
- stm
library:
  source-dirs: src
  exposed-modules:
  - Control.Concurrent.NQE
  dependencies:
  - base >=4.7 && <5
  - containers
  - lifted-async
  - lifted-base
  - transformers-base
  - monad-control
tests:
  nqe-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >=4.7 && <5
    - nqe
    - exceptions
    - hspec
    - stm-conduit
    - text
